### ISSUE TITLE
Curved cilia give wrong cilia length

### ISSUE THREAD

**Issue by lbozal** [hansenjn/CiliaQ#13]
Hi!! I was just measuring some cilia in cells and I realized that length measurements make sense when cilia are straight but not when they are curved. Is this a common issue? I see that the skeleton of the cilia are correct.

**Comment by lbozal** [comment]
Hi!! Find attached the original picture, the skeleton and the text files containing info and results!
let me know if everything was OK! Thanks for all the support!!

[original pic_CQP_ed_CQ.txt](https://github.com/hansenjn/CiliaQ/files/11212947/original.pic_CQP_ed_CQ.txt)
[original pic_CQP_ed_CQl.txt](https://github.com/hansenjn/CiliaQ/files/11212954/original.pic_CQP_ed_CQl.txt)
[original pic_CQP_ed_CQs.txt](https://github.com/hansenjn/CiliaQ/files/11212955/original.pic_CQP_ed_CQs.txt)
[original pic_CQP_ed_CQ_SKL_info.txt](https://github.com/han
[original pic_CQP_ed.txt](https://github.com/hansenjn/CiliaQ/files/11212957/original.pic_CQP_ed.txt)
senjn/CiliaQ/files/11212956/original.pic_CQP_ed_CQ_SKL_info.txt)

**Comment by lbozal** [comment]
![original pic](https://user-images.githubusercontent.com/81254767/231503184-ada9b9e6-5716-4ee1-b848-f19a64f0adb2.jpg)


Here it is the original picture!

**Comment by lbozal** [comment]
![original pic_CQP_ed_CQ_SKL](https://user-images.githubusercontent.com/81254767/231503831-6199f0c1-66f6-4f5e-8513-b008da058586.png)

And here the skeleton

**Comment by hansenjn** [comment]
Dear @lbozal,

sorry for my very late reply. I got too busy with some other projects and lacked the time to look into the problem.
I do not clearly see the issue you mentioned. There may be tiny differences in length estimates when manually measuring the skeleton lengths to what CiliaQ measures, since CiliaQ upscales the image and blurs it for improved detection of the skeleton.

Could you point me to one of these example cilia, where you think that the length is inaccurately measured and to another one where you think the length is accurately measured? And could you draw/explain exactly how you measure the different cilium length compared to how CiliaQ measures it? Do you measure the actual length in the original image or in the skeleton?

Besides that I have now also released an improved version of CiliaQ that gives even better length estimates than the previous versions, especially in 2D images. Maybe you could also try whether this version gives you a better result.

Best wishes

**Comment by hansenjn** [comment]
Testing the new version with your image, the results seemed accurate in my hands.

**Comment by lbozal** [comment]
Good afternoon!!

- We measured 3 different conditions: WT, MIB1KO, USP21KO
- We did the CiliaQ analysis, which provided the SKL.tif files and the .txt files with the data (find this material in the link)
- We represented the “cilia length [inch] (largest shortest path of largest skeleton)” parameter given by CiliaQ. The graphs by Prism had some empty spaces and did not make sense to us, as we expected a distribution of lengths along the Y axis.
- We also took manual measurements with the segmented line tool in FIJI and represented them and we finally fed the SKL images to the ALPACA program. Both manual and ALPACA gave similar results, which were not similar to CiliaQ. Find the comparison of the 3 graphs in the link.

Link:
https://we.tl/t-qptki2ElQ0

**Comment by hansenjn** [comment]
Hi @lbozal,

thank you so much for your help, for reporting and helping to find the issue. And also for being so cooperative in sharing your data. That helped a lot. I now have found the problem. Sorry that I did not clearly see it yesterday, now I see it.

The old CiliaQ versions (v0.1.4 and earlier) could apparently not accurately enough measure the length in your type of image (2D, low pixel length of 0.003 µm/px). Due to the way the length measurements were implemented in the previous versions, the measurements had a high variance for 2D images, especially with low pixel sizes. I tried to explain it in more detail in the release notes for the newest release: https://github.com/hansenjn/CiliaQ/releases/tag/v0.1.7. It is unfortunately very complicated since this was relating to the way the length measurements were implemented programmatically. Since I have not had images with that conditions before and mostly worked with 3D images for developing CiliaQ, I had never seen the problem before but I understand it now. So it was very valuable to have your image and test the new version with this.

I have worked on improving the length measurements and now released the updated version that has no longer the issue and gives more accurate length measurements. If you install v0.1.7 you should no longer have the problem and get accurate results.

Thank you very much for your help in making CiliaQ better! Don't mind reaching out again if you encounter more issues!

**Comment by lbozal** [comment]
Thanks a lot!! I will definitely try it and come back to you!!
