### ISSUE TITLE
CiliaQ produces empty output file

### ISSUE THREAD

**Issue by sRassmann** [hansenjn/CiliaQ#3]
CiliaQ constantly produces empty output txt and no skeleton file for certain file (provided privately).

**Comment by hansenjn** [comment]
This issue was not originating from CiliaQ but from the configuration of the file. The file was supposed to be handled as a "3D stack" with multiple slices and one timepoint but was erroneously defined as a "timelapse 2D stack" with one slice and multiple timepoints. In ImageJ, this is visualized at the bars below the image:
- This is a stack with multiple channels and multiple time steps (see play button):
![grafik](https://user-images.githubusercontent.com/27991883/81906258-414f4a00-95c6-11ea-935c-6cba92adb4ec.png)
- This is a stack with multiple channels and mulitple slices (see "z"):
![grafik](https://user-images.githubusercontent.com/27991883/81905430-f84ac600-95c4-11ea-90ee-29beec128ab7.png)

As a note: For timelapse stacks, CiliaQ only outputs time-averages for a cilium in the main output file, if the cilium is present in all time frames.
